CREATE TABLE Review(
accountID INT,
isbn varCHAR(13), 
rating INT,
review varCHAR(255), 
PRIMARY KEY (accountID, isbn), 
FOREIGN KEY (accountID) REFERENCES Members(accountID) 
ON UPDATE CASCADE
ON DELETE CASCADE,
FOREIGN KEY (isbn) REFERENCES Book(isbn)
ON UPDATE CASCADE
ON DELETE CASCADE
);
